### ISSUE TITLE
errors when submitting job with "0" edgechannels

### ISSUE THREAD

**Issue by adityajnhs** [MWATelescope/manta-ray-client#30] opened 2020-06-24 08:52 UTC
We submitted a job with "0" edgewidth, but we are getting the following errors:

manta-ray-client version 1.0.0
Connecting to MWA ASVO (asvo.mwatelescope.org:8778)...
Connected to MWA ASVO
Error submitting job #1 from csvfile. Details below:
{"error_code": 0, "error": "Edge Width: Expected > 0"}

We have conducted observations to search for HI 21 cm line in absorption (project D0027). We will lose the line data if we flag 80 kHz channels in each coarse channel of 1.28 MHz, in the 30.7 MHz band. So, we like to opt for "0" kHz edge channel.

We request you to look into this issue.

**Comment by gsleap** [comment] 2020-06-25 03:41
Duplicate of #26

**Closed as completed by gsleap** 2020-06-25 03:41 UTC
Labels: duplicate
